# Generated by Django 2.2.24 on 2024-10-08 16:37

from django.db import migrations


def fill_flat_data_eith_construction_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20241001_1947'),
    ]

    operations = [
        migrations.RunPython(fill_flat_data_eith_construction_year)
    ]
