# Generated by Django 2.2.24 on 2024-11-12 15:42

from django.db import migrations, models, transaction


def migrate_owners_to_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flat_objects = Flat.objects.all()
    for flat_object in flat_objects.iterator():
        Owner.objects.get_or_create(owner=flat_object.owner,
                                    owners_phonenumber=flat_object.owners_phonenumber,
                                    owner_pure_phone=flat_object.owner_pure_phone)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20241112_1831'),
    ]

    operations = [
        migrations.RunPython(migrate_owners_to_owner_model),
    ]
