# Generated by Django 2.2.24 on 2024-12-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20241112_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.CharField('ФИО владельца', max_length=200, db_index=True),
        ),
    ]
