# Generated by Django 2.2.24 on 2024-12-14 09:09

from django.db import migrations, transaction


def bond_flats_to_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner.flats.set(Flat.objects.filter(owner=owner.full_name))


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().update(flats = [])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20241203_1943'),
    ]

    operations = [
        migrations.RunPython(bond_flats_to_owners, move_backward),
    ]
